spring:
  application.name: roba-budgets-server

  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    url: jdbc:postgresql://localhost:5432/roba_budgets
    user: ${DB_USERNAME:roba}
    password: ${DB_PASSWORD:budgets}
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/roba_budgets
    username: ${DB_USERNAME:roba}
    password: ${DB_PASSWORD:budgets}

  webflux:
    problemdetails:
      enabled: true
